### ISSUE TITLE
Idk what to do i tried to restart but it didnt solve. ( Part 5 Detect faces on example images )

### ISSUE THREAD

**Issue by DaviJh** [Maximax67/LoRA-Dataset-Automaker#1] opened 2023-09-24 01:41 UTC
![Screenshot_59](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/75020215/82cb84ff-64ef-45f7-9968-491c33b6b022)
![Screenshot_60](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/75020215/de9545f7-b3d2-44fd-8ee3-b71fc9711798)

**Comment by Maximax67** [comment] 2023-09-25 13:43
Ok. I will check it now. One of your example image is in rgba format (png), and it cannot write it to a jpg file (looks like something is wrong with convertion to RGB format). Probably this line of my code is not working porperly:
`cropped_image = cropped_image.convert("RGB")`

I will check my code and update it to fix this issue it will take 1-2 days. If you want to try again without waiting for my correction, you can remove (or not add) your png example image. Thanks for reporting the issue!

**Comment by DaviJh** [comment] 2023-09-25 17:19
> Ok. I will check it now. One of your example image is in rgba format (png), and it cannot write it to a jpg file (looks like something is wrong with convertion to RGB format). Probably this line of my code is not working porperly: `cropped_image = cropped_image.convert("RGB")`
> 
> I will check my code and update it to fix this issue it will take 1-2 days. If you want to try again without waiting for my correction, you can remove (or not add) your png example image. Thanks for reporting the issue!

oh ok thx btw what would be the best to train a style just download all imagens from anime and train it? i mean its possible only download all images from anime on fancaps without select example faces because i dont see any option to export to google drive

**Comment by Maximax67** [comment] 2023-09-27 08:41
Hi, can you send the example images that caused the error or links to them? I can't reproduce the bug.

Yes, you can train the style. You can save your project to Google Drive. The downloaded images will be in the scrapped folder. Filtered from duplicates in the filtered folder. I will add the ability to export a zip file to Google Drive of only downloaded images along with the solution to your problem.

**Comment by DaviJh** [comment] 2023-09-27 18:53
> Hi, can you send the example images that caused the error or links to them? I can't reproduce the bug.
> 
> Yes, you can train the style. You can save your project to Google Drive. The downloaded images will be in the scrapped folder. Filtered from duplicates in the filtered folder. I will add the ability to export a zip file to Google Drive of only downloaded images along with the solution to your problem.

i used two images from pinterest on example images i dont have them anymore i just copied the links and tried to continue. When I saw it wasn't running I tried training with another character and works. it was probably the pinterest images I tried to use cause the error

**Comment by DaviJh** [comment] 2023-09-27 18:54
" will add the ability to export a zip file to Google Drive of only downloaded images along with the solution to your problem. "

will help alot to make styles thx man

**Comment by DaviJh** [comment] 2023-09-27 19:11
> Hi, can you send the example images that caused the error or links to them? I can't reproduce the bug.
> 
> Yes, you can train the style. You can save your project to Google Drive. The downloaded images will be in the scrapped folder. Filtered from duplicates in the filtered folder. I will add the ability to export a zip file to Google Drive of only downloaded images along with the solution to your problem.

this happened right now trying download anime images maybe its because i think you make some changes:
![image](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/75020215/0575996a-a011-4aad-8c31-291a2210c07a)
27/09/2023 - 15:10

**Comment by Maximax67** [comment] 2023-09-27 20:10
"i used two images from pinterest" - ok, will check some of them!
"will help alot to make styles" - will update my code tomorrow! Will add this and many new features!

**Comment by Maximax67** [comment] 2023-09-28 12:17
Hi, I udated my code. I added zipping custom folder (step 6.2). You can zip any folder by writing path to it (just copy what path you need from step 1.5):
<img width="575" alt="image" src="https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/40457162/42e472d7-025e-4b96-a88c-15544aa55f40">

I updated some code which may lead to bug with saving cropped faces. If you encounter another bug, open new issue here on github.

**Closed as completed by Maximax67** 2023-09-28 12:17 UTC

**Comment by DaviJh** [comment] 2023-09-28 15:55
> Hi, I udated my code. I added zipping custom folder (step 6.2). You can zip any folder by writing path to it (just copy what path you need from step 1.5): <img alt="image" width="575" src="https://user-images.githubusercontent.com/40457162/271279487-42e472d7-025e-4b96-a88c-15544aa55f40.png">
> 
> I updated some code which may lead to bug with saving cropped faces. If you encounter another bug, open new issue here on github.

Nice! ok thx
